# 注册服务的IP
ip_to_register: "127.0.0.1"

mysql:
  host: 127.0.0.1
  port: 3306
  user: "xservergo"
  password: "xservergo"
  dbname: "xservergo"
  max_open_conns: 20
  max_idle_conns: 20

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  pool_size: 100
  min_idle_conns: 10

qrredis:
  host: 127.0.0.1
  port: 6380
  password: ""
  db: 0
  pool_size: 100
  min_idle_conns: 10

jwt:
  # 设置jwt签名加密时使用的前端秘钥
  admin_secret_key: "default_admin_secret_key_change_in_production"
  # 设置AccessToken的有效时间（秒）
  access_token_ttl: 3600
  # 设置RefreshToken的有效时间（秒）
  refresh_token_suv: 604800

elasticsearch:
  hosts:
    - "http://127.0.0.1:9200"
  username: ""
  password: ""

etcd:
  endpoints: 
    - "127.0.0.1:2379"
  username: "root"
  password: "xservergo"

hertz:
  host: 127.0.0.1
  port: 8080

user:
  host: 127.0.0.1
  port: 8900
  service_name: "user_service"

auth:
  host: 127.0.0.1
  port: 8901
  service_name: "auth_service"

file:
  host: 127.0.0.1
  port: 8902
  service_name: "xservergo.file"
  file_store_position: "C:\\temp" #存储分片的绝对路径,必填

logger:
  stdout:
    allowed: true    # 控制台输出
    level: "info"    # 输出级别
  file_output:
    allowed: true    # 文件输出
    access_path: "./log/access.log" #输出路径，默认为./log/access.log
    max_size: 100     # MB
    max_backups: 14   # 保留两周日志
    max_age: 14       # 自动删除14天前的日志
    compress: false   # 压缩归档
    level: "info"     # 输出级别
  sample_initial: 100 # 每秒100条开始采样
  sample_burst: 200   # 突发流量200条