# 注册服务的IP
ip_to_register: "127.0.0.1"

mysql:
  host: localhost
  port: 3306
  user: "root"
  password: "your_pwd"
  dbname: "database_name"
  max_open_conns: 20
  max_idle_conns: 20

redis:
  host: localhost
  port: 6379
  password: "your_pwd"
  db: 0
  pool_size: 100

jwt:
  # 设置jwt签名加密时使用的前端秘钥
  admin_secret_key: "your_admin_secret_key"
  # 设置jwt签名加密时使用的后端秘钥
  service_secret_key: "your_service_secret_key"
  # 设置jwt过期时间为7天
  admin_ttl: 0
  admin_suv: 0

elasticsearch:
  hosts:
    - "http(s)://address:port"
  username: "your_username"
  password: "your_pwd"

etcd:
  endpoints: localhost:2379
  username: "your_username"
  password: "your_pwd"

hertz:
  host: 127.0.0.1
  port: 0

user:
  host: 127.0.0.1
  port: 0
  service_name: "your_service_name"

logger:
  stdout:
    allowed: true    # 控制台输出
    level: "info"    # 输出级别
  file_output:
    allowed: true    # 文件输出
    access_path: "./log/access.log" #输出路径，默认为./log/access.log
    max_size: 100     # MB
    max_backups: 14   # 保留两周日志
    max_age: 14       # 自动删除14天前的日志
    compress: false   # 压缩归档
    level: "info"     # 输出级别
  sample_initial: 100 # 每秒100条开始采样
  sample_burst: 200   # 突发流量200条